---
name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint / Format / Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - "24.x"
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v6.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Build (dev)
        run: npm run build
